### ISSUE TITLE
로그인 (web02)

### ISSUE THREAD

**Issue by EomHyeYeong** [boiled-potatoes-kdt/be#15]
*일반 로그인일 경우 아이디(이메일)과 비밀번호로 로그인 할 수 있도록 함*

### 1. 아이디(이메일) 입력
- 인풋 텍스트박스
- 문자 종류 제한 없음
- 100자까지 입력 가능

### 2. 비밀번호 입력
- 인풋 텍스트박스, , 암호화(*) 표시, 
- 영문/숫자 50자까지 입력 가능(8자 이상의 영문, 숫자, 특수문자 중 2가지 이상 조합)

### 3. 로그인 버튼
- 가입된 아이디와 비밀번호 입력 후 클릭 시 로그인 처리 & 기존 페이지로 이동
- 아이디/비밀번호가 틀렸을 경우 얼러트 창 생성 ‘아이디/비밀번호를 확인해주세요’ > 확인(버튼)

### 4. 아이디 찾기
- 아이디 찾기 페이지로 이동 (화면 ID web 03)

### 5. 비밀번호 찾기
- 비밀번호 찾기 페이지로 이동 (화면 ID web 05)

### 6. SNS 로그인
- 클릭 시 각 플랫폼(카카오, 네이버, 구글) 각각 3가지 소셜 로그인 모듈 호출

### 7. 회원가입 버튼
- 회원가입 페이지로 이동 (화면 ID web 07)

![Image](https://github.com/user-attachments/assets/3e602976-0a3a-404f-9bc5-adf5a2485e0b)

![Image](https://github.com/user-attachments/assets/aef1ab6a-8fdb-4910-9204-71037f540f89)

**Comment by Domae-back-end** [comment]
@minnug-dev 백엔드 자체 로그인은 끝났습니다. 소셜 로그인은 내일 작업 할예정입니다.

**Comment by minnug-dev** [comment]
> [@minnug-dev](https://github.com/minnug-dev) 백엔드 자체 로그인은 끝났습니다. 소셜 로그인은 내일 작업 할예정입니다.

**Comment by minnug-dev** [comment]
넵! 알겠습니다
