### ISSUE TITLE
맞팔/서이추(web 31)

### ISSUE THREAD

**Issue by Song-Mins** [boiled-potatoes-kdt/be#46]
1. 맞팔/서이추 게시판 :
- 목록 페이지부터 닉네임/업체명이 등록된 회원만 이용 가능
- 프로필 미등록 회원에게 안내창 표시 '프로필 등록 후 이용 가능합니다.' 
- 미회원 화면 ID 2 로그인 화면으로 이동
- 사업주 회원의 경우 업체명을 닉네임으로 사용
- 가장 최근 등록한 글(등록일 기준)이 최상단에 위치

2. 검색 :
- 제목, 작성자, 내용에서 검색
- 검색란은 최소 2글자, 최대 30자까지 입력 가능

3. 글작성 버튼 :
- 클릭 시 화면 ID 44 글 작성 페이지로 이동

4. 카테고리 :
- 카테고리를 표시
-블로그, 인스타그램, 틱톡, 유튜브, 기타

5. 제목 :
- 글 제목을 표시
- 제목이 긴 경우 줄임표로 표시

6. 작성자 :
- 작성자를 표시
- 인플루언서 회원인 경우 닉네임 표시
- 사업주 회원인 경우 업체명 표시

7. 등록일 :
- 글 등록일을 연월일까지 표시

8. 조회수 :
- 조회수를 숫자로만 표시
- 1000 단위 구분점 표시

9. 댓글수 :
- 댓글수를 숫자로만 표시
- 1000 단위 구분점 표시

10. 페이지네이션:
- 한 페이지당 10개 항목을 표시
- 클릭해서 페이지 이동 가능
- 선택된 페이지는 색상 변경 등으로 하이라이트 처리

11. 내용 미리보기:
- 글 내용을 표시
- 내용이 긴 경우 한 줄이 넘어가면  줄임표로 표시

![Image](https://github.com/user-attachments/assets/22159bf0-b7e4-4f16-af49-d605409dfaf9)

![Image](https://github.com/user-attachments/assets/f87df456-05a8-48d8-9386-3e60f9b33cdb)

**Comment by DAHYE1212** [comment]
카테고리: 블로그, 인스타그램, 틱톡,유튜브,기타
